"""Lead data model for MongoDB."""
from typing import Optional
from datetime import date


class Lead:
    """Lead model representing a lead in the database."""

    def __init__(
        self,
        name: str,
        email: str,
        phone: str,
        birth_date: Optional[str] = None,
        id: Optional[str] = None,
    ):
        """
        Initialize a Lead instance.

        Args:
            name: Lead's full name
            email: Lead's email address
            phone: Lead's phone number
            birth_date: Lead's birth date (optional, fetched from external API)
            id: Lead's unique identifier (generated by MongoDB)
        """
        self.id = id
        self.name = name
        self.email = email
        self.phone = phone
        self.birth_date = birth_date

    def to_dict(self) -> dict:
        """
        Convert Lead instance to dictionary.

        Returns:
            Dictionary representation of the lead
        """
        return {
            "id": self.id,
            "name": self.name,
            "email": self.email,
            "phone": self.phone,
            "birth_date": self.birth_date,
        }

    @staticmethod
    def from_dict(data: dict) -> "Lead":
        """
        Create Lead instance from dictionary.

        Args:
            data: Dictionary containing lead data

        Returns:
            Lead instance
        """
        return Lead(
            id=str(data.get("_id", "")),
            name=data.get("name", ""),
            email=data.get("email", ""),
            phone=data.get("phone", ""),
            birth_date=data.get("birth_date"),
        )
